# Generated by Django 2.2.13 on 2021-04-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210423_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='n',
            field=models.CharField(default='patient', max_length=50),
        ),
    ]
