# Generated by Django 2.2.13 on 2021-04-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_visit_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='vtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
