# Generated by Django 2.2.13 on 2021-05-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210502_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='lap',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lap01',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='sonar',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='sonar01',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='sonar02',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='sonar03',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
    ]
