# Generated by Django 2.2.13 on 2021-05-13 06:33

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_vitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='vItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
