# Generated by Django 2.2.13 on 2021-05-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_coment_coment1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maqal',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='maqal',
            name='pic2',
        ),
    ]
