# Generated by Django 2.2.13 on 2021-04-23 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210416_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='phone',
        ),
    ]
