# Generated by Django 2.2.13 on 2021-04-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_visit_vtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='important_ad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
