# Generated by Django 2.2.13 on 2021-05-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_visit_important_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='lap',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='lap01',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='sonar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='sonar01',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='sonar02',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='sonar03',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
