# Generated by Django 2.2.13 on 2021-05-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210502_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='lap',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='lap01',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='sonar',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='sonar01',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='sonar02',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='sonar03',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
    ]
