# Generated by Django 2.2.13 on 2021-05-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210502_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='fourth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, default='1234.jpg', null=True, upload_to='')),
                ('pic2', models.ImageField(blank=True, default='1234.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='frist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, default='1234.jpg', null=True, upload_to='')),
                ('pic2', models.ImageField(blank=True, default='1234.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='scond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, default='1234.jpg', null=True, upload_to='')),
                ('pic2', models.ImageField(blank=True, default='1234.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='third',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, default='1234.jpg', null=True, upload_to='')),
                ('pic2', models.ImageField(blank=True, default='1234.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='visit',
            name='vtime',
        ),
        migrations.AddField(
            model_name='maqal',
            name='pic2',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitem',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maqal',
            name='pic',
            field=models.ImageField(blank=True, default='1234.jpg', null=True, upload_to=''),
        ),
    ]
