# Generated by Django 2.2.13 on 2021-05-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210513_0612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vItem',
        ),
    ]
